spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true # 콘솔에 SQL 쿼리를 출력할지 여부를 결정
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true # SQL 쿼리를 보기 좋게 포맷팅