jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/google" # 인증 후 사용자가 리디렉션될 URI , /oauth2/authorization/google (요청)
            scope: # google API의 범위 값
              - profile
              - email
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao" # 인증 후 사용자가 리디렉션될 URI , /oauth2/authorization/kakao (요청)
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: # kakao 개인 정보 동의 항목 설정의 ID 값
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao

        provider: # OAuth 2.0 제공자의 엔드포인트를 정의
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth # 사용자를 인증하기 위한 URI
            token-uri: https://oauth2.googleapis.com/token # 액세스 토큰을 발급받기 위한 URI
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo # 사용자 정보를 가져오기 위한 URI
            user-name-attribute: sub # 사용자 정보에서 사용자 이름으로 사용할 속성
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header # 토큰을 보내는 방법 header, form, query 중 header가 기본 값
            user_name_attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정
