spring:
  application:
    name: Be
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  config:
    import:
      - config/application-api.yml
      - config/application-database.yml
      - config/application-security.yml
